#!/usr/bin/env bash
# handoff.sh — regenerate the machine-managed blocks in docs/handoff/SESSION-HANDOFF.md (and the
# AUTO-INVENTORY block in architecture/README.md) so the cold-start map + handoff stay truthful without
# anyone rewriting them. land.sh calls this after every merge; run it manually any time. Only text BETWEEN
# the AUTO-* markers is touched — the narrative around them stays hand-written.
#   AUTO-STATE     — main / branch / active specs / open PRs / last ledger events (snapshot; handoff only)
#   AUTO-SHIPPED   — completed task specs (optional block; handoff only)
#   AUTO-INVENTORY — components → profile + built/stub, available profiles (handoff + architecture/README)
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; source "$DIR/_lib.sh"
cd "$(repo_root)"

doc="docs/handoff/SESSION-HANDOFF.md"
[[ -f "$doc" ]] || die "missing $doc" \
  "the handoff doc was moved, renamed, or not created yet" \
  "restore it:  git checkout -- $doc   (or fix the path at the top of scripts/handoff.sh)"
grep -q 'AUTO-STATE:BEGIN' "$doc" || die "$doc has no AUTO-STATE markers" \
  "a hand-edit removed the managed-block markers" \
  "re-add  <!-- AUTO-STATE:BEGIN ... -->  and  <!-- AUTO-STATE:END -->  (see this script's header)"

# replace_block <doc> <TAG> <contentfile> — swap text between <TAG>:BEGIN and <TAG>:END.
replace_block() {
  local d="$1" tag="$2" f="$3"
  awk -v f="$f" -v b="${tag}:BEGIN" -v e="${tag}:END" '
    index($0,b){ while ((getline l < f) > 0) print l; close(f); skip=1; next }
    index($0,e){ skip=0; next }
    !skip
  ' "$d" > "${d}.new" && mv "${d}.new" "$d"
}

# gen_inventory + block_inclusive now live in _lib.sh (shared with verify-coherence.sh — ADR-0018).

shopt -s nullglob
active=( tasks/active/*.md )
completed=( tasks/completed/*.md )
prs="$(gh pr list --state open --json number,title,headRefName \
  --template '{{range .}}#{{.number}} {{.title}} [{{.headRefName}}]  {{end}}' 2>/dev/null || true)"

# --- AUTO-STATE -------------------------------------------------------------
state="$(mktemp)"
{
  echo "<!-- AUTO-STATE:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
  echo "- **main:** \`$(git log -1 --format='%h %s' main)\`"
  echo "- **checked-out branch:** \`$(git branch --show-current)\` · worktree: $([[ -n "$(git status --porcelain)" ]] && echo "DIRTY (expected right after handoff.sh ran — the refresh itself is the diff; it rides along with the next PR)" || echo clean)"
  echo "- **active task specs:** ${active[*]:-none} · completed: ${#completed[@]}"
  echo "- **open PRs:** ${prs:-none}"
  echo "- **last ledger events:**"
  echo '```'
  tail -n 6 "$(ledger_path)" 2>/dev/null || echo "(no ledger yet)"
  echo '```'
  echo "<!-- AUTO-STATE:END -->"
} > "$state"
replace_block "$doc" 'AUTO-STATE' "$state"; rm -f "$state"

# --- AUTO-SHIPPED (only if the doc opts in by including the markers) --------
if grep -q 'AUTO-SHIPPED:BEGIN' "$doc"; then
  shipped="$(mktemp)"
  {
    echo "<!-- AUTO-SHIPPED:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
    if (( ${#completed[@]} )); then
      for f in "${completed[@]}"; do
        tid="$(fm_scalar "$f" id)";     tid="${tid//\"/}"
        tslug="$(fm_scalar "$f" slug)"; tslug="${tslug//\"/}"
        echo "- **${tid:-?} — ${tslug:-$(basename "$f" .md)}** → completed"
      done
    else
      echo "- (no completed task specs yet)"
    fi
    echo "<!-- AUTO-SHIPPED:END -->"
  } > "$shipped"
  replace_block "$doc" 'AUTO-SHIPPED' "$shipped"; rm -f "$shipped"
fi

# --- AUTO-INVENTORY — generated once, injected into every doc that opts in (handoff + architecture/README) -
for _tgt in "$doc" "architecture/README.md"; do
  [[ -f "$_tgt" ]] || continue
  grep -q 'AUTO-INVENTORY:BEGIN' "$_tgt" || continue
  inv="$(mktemp)"; gen_inventory > "$inv"; replace_block "$_tgt" 'AUTO-INVENTORY' "$inv"; rm -f "$inv"
done

log "refreshed managed blocks (handoff AUTO-STATE/SHIPPED + AUTO-INVENTORY in handoff & architecture/README)"
