#!/usr/bin/env bash
# handoff.sh — regenerate the AUTO-STATE block in docs/handoff/SESSION-HANDOFF.md so the
# cold-start doc stays truthful without anyone rewriting it. land.sh calls this after
# every merge; run it manually any time. Only the text between the AUTO-STATE markers
# is touched — the narrative around it stays hand-written.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; source "$DIR/_lib.sh"
cd "$(repo_root)"

doc="docs/handoff/SESSION-HANDOFF.md"
[[ -f "$doc" ]] || die "missing $doc"
grep -q 'AUTO-STATE:BEGIN' "$doc" || die "$doc has no AUTO-STATE markers — add them (see scripts/handoff.sh header)"

shopt -s nullglob
active=( tasks/active/*.md )
completed=( tasks/completed/*.md )
prs="$(gh pr list --state open --json number,title,headRefName \
  --template '{{range .}}#{{.number}} {{.title}} [{{.headRefName}}]  {{end}}' 2>/dev/null || true)"

block="$(mktemp)"
{
  echo "<!-- AUTO-STATE:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
  echo "- **main:** \`$(git log -1 --format='%h %s' main)\`"
  echo "- **checked-out branch:** \`$(git branch --show-current)\` · worktree: $([[ -n "$(git status --porcelain)" ]] && echo "DIRTY (expected right after handoff.sh ran — the refresh itself is the diff; it rides along with the next PR)" || echo clean)"
  echo "- **active task specs:** ${active[*]:-none} · completed: ${#completed[@]}"
  echo "- **open PRs:** ${prs:-none}"
  echo "- **last ledger events:**"
  echo '```'
  tail -n 6 "$(ledger_path)" 2>/dev/null || echo "(no ledger yet)"
  echo '```'
  echo "<!-- AUTO-STATE:END -->"
} > "$block"

awk -v f="$block" '
  /AUTO-STATE:BEGIN/ { while ((getline l < f) > 0) print l; close(f); skip=1; next }
  /AUTO-STATE:END/   { skip=0; next }
  !skip
' "$doc" > "${doc}.new"
mv "${doc}.new" "$doc"
rm -f "$block"
log "refreshed AUTO-STATE in $doc"
