#!/usr/bin/env bash
# handoff.sh — regenerate the machine-managed blocks in docs/handoff/SESSION-HANDOFF.md so the
# cold-start doc stays truthful without anyone rewriting it. land.sh calls this after every merge;
# run it manually any time. Only text BETWEEN the AUTO-* markers is touched — the narrative around
# them stays hand-written.
#   AUTO-STATE   — main / branch / active specs / open PRs / last ledger events (snapshot)
#   AUTO-SHIPPED — the list of completed task specs, so §4's facts can't go stale (optional block)
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; source "$DIR/_lib.sh"
cd "$(repo_root)"

doc="docs/handoff/SESSION-HANDOFF.md"
[[ -f "$doc" ]] || die "missing $doc" \
  "the handoff doc was moved, renamed, or not created yet" \
  "restore it:  git checkout -- $doc   (or fix the path at the top of scripts/handoff.sh)"
grep -q 'AUTO-STATE:BEGIN' "$doc" || die "$doc has no AUTO-STATE markers" \
  "a hand-edit removed the managed-block markers" \
  "re-add  <!-- AUTO-STATE:BEGIN ... -->  and  <!-- AUTO-STATE:END -->  (see this script's header)"

# replace_block <doc> <TAG> <contentfile> — swap text between <TAG>:BEGIN and <TAG>:END.
replace_block() {
  local d="$1" tag="$2" f="$3"
  awk -v f="$f" -v b="${tag}:BEGIN" -v e="${tag}:END" '
    index($0,b){ while ((getline l < f) > 0) print l; close(f); skip=1; next }
    index($0,e){ skip=0; next }
    !skip
  ' "$d" > "${d}.new" && mv "${d}.new" "$d"
}

shopt -s nullglob
active=( tasks/active/*.md )
completed=( tasks/completed/*.md )
prs="$(gh pr list --state open --json number,title,headRefName \
  --template '{{range .}}#{{.number}} {{.title}} [{{.headRefName}}]  {{end}}' 2>/dev/null || true)"

# --- AUTO-STATE -------------------------------------------------------------
state="$(mktemp)"
{
  echo "<!-- AUTO-STATE:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
  echo "- **main:** \`$(git log -1 --format='%h %s' main)\`"
  echo "- **checked-out branch:** \`$(git branch --show-current)\` · worktree: $([[ -n "$(git status --porcelain)" ]] && echo "DIRTY (expected right after handoff.sh ran — the refresh itself is the diff; it rides along with the next PR)" || echo clean)"
  echo "- **active task specs:** ${active[*]:-none} · completed: ${#completed[@]}"
  echo "- **open PRs:** ${prs:-none}"
  echo "- **last ledger events:**"
  echo '```'
  tail -n 6 "$(ledger_path)" 2>/dev/null || echo "(no ledger yet)"
  echo '```'
  echo "<!-- AUTO-STATE:END -->"
} > "$state"
replace_block "$doc" 'AUTO-STATE' "$state"; rm -f "$state"

# --- AUTO-SHIPPED (only if the doc opts in by including the markers) --------
if grep -q 'AUTO-SHIPPED:BEGIN' "$doc"; then
  shipped="$(mktemp)"
  {
    echo "<!-- AUTO-SHIPPED:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
    if (( ${#completed[@]} )); then
      for f in "${completed[@]}"; do
        tid="$(fm_scalar "$f" id)";     tid="${tid//\"/}"
        tslug="$(fm_scalar "$f" slug)"; tslug="${tslug//\"/}"
        echo "- **${tid:-?} — ${tslug:-$(basename "$f" .md)}** → completed"
      done
    else
      echo "- (no completed task specs yet)"
    fi
    echo "<!-- AUTO-SHIPPED:END -->"
  } > "$shipped"
  replace_block "$doc" 'AUTO-SHIPPED' "$shipped"; rm -f "$shipped"
fi

# --- AUTO-INVENTORY (components → profiles, + available profiles) — scales to many ----
if grep -q 'AUTO-INVENTORY:BEGIN' "$doc"; then
  inv="$(mktemp)"; bt='`'
  {
    echo "<!-- AUTO-INVENTORY:BEGIN — generated by scripts/handoff.sh @ $(date -u +%FT%TZ); do not hand-edit -->"
    echo "**Components (the deliverables built by the system):**"
    cfound=0
    for d in components/*/; do
      [[ -d "$d" ]] || continue
      cn="${d#components/}"; cn="${cn%/}"
      cprof="(no .component.yml)"
      [[ -f "${d}.component.yml" ]] && cprof="$(fm_scalar "${d}.component.yml" profile)"
      echo "- ${bt}${cn}${bt} → profile ${bt}${cprof:-?}${bt}"; cfound=1
    done
    (( cfound )) || echo "- (none yet)"
    echo
    echo "**Profiles available** (each a fixed-catalog binding under ${bt}profiles/<family>/<variant>/${bt}):"
    pfound=0
    for p in profiles/*/*/; do
      [[ -f "${p}profile.json" ]] || continue
      pn="${p#profiles/}"; pn="${pn%/}"
      echo "- ${bt}${pn}${bt}"; pfound=1
    done
    (( pfound )) || echo "- (none yet)"
    echo "<!-- AUTO-INVENTORY:END -->"
  } > "$inv"
  replace_block "$doc" 'AUTO-INVENTORY' "$inv"; rm -f "$inv"
fi

log "refreshed managed blocks in $doc"
